module.exports = [
    {
        ETD: '2300',
        number: '482',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Maria Clayton',
        FO: 'George Combs',
        status: true,
    },
    {
        ETD: '1230',
        number: '325',
        aircraft: 'E55P',
        reg:'N7438D',
        dep: 'KBOS',
        dest: 'KDTW',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Dalton Maddox',
        FO: 'Amy Walker',
        status: false,
    },
    {
        ETD: '1120',
        number: '837',
        aircraft: 'CL30',
        reg:'N362GJ',
        dep: 'KCVG',
        dest: 'KPHX',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Raymond Fleming',
        FO: 'Eusebio Harvey',
        status: false,
    },
    {
        ETD: '2003',
        number: '724',
        aircraft: 'C68A',
        reg:'N712HK',
        dep: 'KBDL',
        dest: 'KDCA',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Lavern Ross',
        FO: 'Willian Houston',
        status: true,
    },
    {
        ETD: '2250',
        number: '364',
        aircraft: 'GL7T',
        reg:'N1278A',
        dep: 'KOAK',
        dest: 'KRNO',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Von Saunders',
        FO: 'Christian Rivera',
        status: true,
    },
    {
        ETD: '1345',
        number: '1208',
        aircraft: 'C700',
        reg:'N637KC',
        dep: 'KDAL',
        dest: 'KMSY',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Wilson Lambert',
        FO: 'Nolan Patton',
        status: true,
    },
    {
        ETD: '1435',
        number: '982',
        aircraft: 'PC12',
        reg:'N453CS',
        dep: 'KMCI',
        dest: 'KSAV',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'Mikel Newman',
        FO: 'Nathanial Sosa',
    },
]