module.exports = [
    {
        ETD: '2300',
        number: '482',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '325',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '837',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '724',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '364',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '1208',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
    {
        ETD: '2300',
        number: '982',
        aircraft: 'PC12',
        reg:'N808BL',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
        status: 'FILED',
    },
]