module.exports = [
    {
        number: '4312',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '317',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '791',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '938',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '537',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '35',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
    {
        number: '482',
        aircraft: 'PC12',
        dep: 'KBOS',
        dest: 'KTEB',
        maxAlt: '35000',
        route: 'BLZZR5 BLZZR BAF MOBBS SAGES V489 COATE',
        PIC: 'John Dispatch',
        FO: 'Jason Dispatch',
    },
]